/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ParteDetailCard: typeof import('./src/components/ParteDetailCard.vue')['default']
    ParteForm: typeof import('./src/components/ParteForm.vue')['default']
    ProveedorForm: typeof import('./src/components/ProveedorForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsuarioForm: typeof import('./src/components/UsuarioForm.vue')['default']
  }
}
